# Generated by Django 6.1.1 on 2026-09-20 11:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizz',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Partida1v1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_j1', models.IntegerField(default=0)),
                ('puntaje_j2', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('esperando', 'Esperando Oponente'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado')], default='esperando', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duelos_ganados', to=settings.AUTH_USER_MODEL)),
                ('jugador_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_como_j1', to=settings.AUTH_USER_MODEL)),
                ('jugador_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_como_j2', to=settings.AUTH_USER_MODEL)),
                ('quizz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.quizz')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_experiencia', models.PositiveIntegerField(default=0)),
                ('victorias_1v1', models.PositiveIntegerField(default=0)),
                ('derrotas_1v1', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
