# Generated by Django 6.1.1 on 2026-09-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_quizz_creado_en_alter_quizz_titulo_partida1v1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida1v1',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
